package gateway

type Route struct {
	Method string
	Path   string
}

var Routes = []Route{
	{Method: "GET", Path: "/api/store-intel/apps/search/cache"},
	{Method: "GET", Path: "/api/store-intel/apps/search"},
	{Method: "GET", Path: "/api/store-intel/apps/{app_id}/cache"},
	{Method: "GET", Path: "/api/store-intel/apps/{app_id}/reviews"},
	{Method: "POST", Path: "/api/store-intel/apps/{app_id}/reviews"},
	{Method: "GET", Path: "/api/store-intel/apps/{app_id}/reviews/cache"},
	{Method: "GET", Path: "/api/store-intel/apps/{app_id}/similar"},
	{Method: "GET", Path: "/api/store-intel/apps/{app_id}/permissions"},
	{Method: "GET", Path: "/api/store-intel/apps/{app_id}"},
	{Method: "GET", Path: "/api/store-intel/charts/cache"},
	{Method: "GET", Path: "/api/store-intel/charts"},
	{Method: "POST", Path: "/api/store-intel/charts/snapshot"},
	{Method: "GET", Path: "/api/store-intel/app-snapshots/history"},
	{Method: "GET", Path: "/api/store-intel/app-snapshots/recent"},
	{Method: "GET", Path: "/api/store-intel/app-snapshots/count"},
	{Method: "POST", Path: "/api/store-intel/chart-rank"},
	{Method: "GET", Path: "/api/store-intel/chart-rank/history"},
	{Method: "POST", Path: "/api/store-intel/keyword-rank"},
	{Method: "GET", Path: "/api/store-intel/keyword-rank/history"},
	{Method: "GET", Path: "/api/store-intel/keyword-rank/recent"},
	{Method: "GET", Path: "/api/store-intel/keyword-coverage/cache"},
	{Method: "POST", Path: "/api/store-intel/keyword-coverage"},
	{Method: "POST", Path: "/api/store-intel/keyword-coverage/stream"},
	{Method: "GET", Path: "/api/store-intel/tracking/apps"},
	{Method: "POST", Path: "/api/store-intel/tracking/apps"},
	{Method: "POST", Path: "/api/store-intel/tracking/apps/remove"},
	{Method: "POST", Path: "/api/store-intel/tracking/apps/enabled"},
	{Method: "POST", Path: "/api/store-intel/tracking/apps/frequency"},
	{Method: "POST", Path: "/api/store-intel/tracking/apps/tag"},
	{Method: "POST", Path: "/api/store-intel/tracking/apps/sync"},
	{Method: "GET", Path: "/api/store-intel/tracking/keywords"},
	{Method: "POST", Path: "/api/store-intel/tracking/keywords"},
	{Method: "POST", Path: "/api/store-intel/tracking/keywords/remove"},
	{Method: "POST", Path: "/api/store-intel/tracking/keywords/enabled"},
	{Method: "POST", Path: "/api/store-intel/tracking/keywords/frequency"},
	{Method: "POST", Path: "/api/store-intel/tracking/keywords/sync"},
	{Method: "GET", Path: "/api/store-intel/tracking/chart-apps"},
	{Method: "POST", Path: "/api/store-intel/tracking/chart-apps"},
	{Method: "POST", Path: "/api/store-intel/tracking/chart-apps/remove"},
	{Method: "POST", Path: "/api/store-intel/tracking/chart-apps/enabled"},
	{Method: "POST", Path: "/api/store-intel/tracking/chart-apps/sync"},
	{Method: "POST", Path: "/api/store-intel/tracking/sync-all"},
	{Method: "GET", Path: "/api/store-intel/alerts"},
	{Method: "POST", Path: "/api/store-intel/alerts/read"},
	{Method: "POST", Path: "/api/store-intel/history/cleanup"},
	{Method: "POST", Path: "/api/store-intel/refresh-jobs"},
	{Method: "GET", Path: "/api/store-intel/refresh-jobs/{job_id}"},
	{Method: "GET", Path: "/api/store-intel/settings"},
	{Method: "POST", Path: "/api/store-intel/settings"},
}
